version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: infodbpass
      MYSQL_DATABASE: info-db
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306" # Accessible from outside (from port 3306)

volumes:
  db: