INSERT INTO information (info)
VALUES ('Sample Data 1'),
       ('Sample Data 2'),
       ('Sample Data 3'),
       ('Sample Data 4'),
       ('Sample Data 5'),
       ('Sample Data 6'),
       ('Sample Data 7'),
       ('Sample Data 8'),
       ('Sample Data 9'),
       ('Sample Data 10'),
       ('Sample Data 11'),
       ('Sample Data 12'),
       ('Sample Data 13'),
       ('Sample Data 14'),
       ('Sample Data 15'),
       ('Sample Data 16'),
       ('Sample Data 17'),
       ('Sample Data 18'),
       ('Sample Data 19'),
       ('Sample Data 20');
